### ISSUE TITLE
Colors in map

### ISSUE THREAD

**Issue by sarahleavitt** [HopkinsIDD/hitRcovid#1]
Can we have the colors match the timeline function?
Strongly implemented: "red"
Partially implemented: "darkorange"
Not implemented: some shade of grey

Then we could have white or very light grey be no data?

It would be good to have a consistent color scheme across the different functions and this was what was chosen for the paper.

**Comment by Hanmeng-Xu** [comment]
Changed the colors of the map to match other functions.
